version: '3.8'

services:
  web:
    image: php:8-apache
    container_name: php-apache-container
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    command: >
      bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge